---
- name: Dotfiles config
  hosts: localhost
  connection: local
  tasks:
    - name: Home directory
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."
    - name: Playbook directory
      ansible.builtin.debug:
        msg: "'{{ playbook_dir }}' is the playbook directory."

    - name: Get user
      become: true # become sudo
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_user_id }}"

    - name: Create Directories
      ansible.builtin.include_tasks: "tasks/directories.yml"

    - name: Clone needed repos
      ansible.builtin.include_tasks: "tasks/clone.yml"

    - name: Symlink configs
      ansible.builtin.include_tasks: "tasks/symlink.yml"

    - name: Install Packages
      ansible.builtin.include_tasks: "tasks/packages.yml"

    - name: Change user default shell to zsh
      become: true # become sudo
      tags:
        - zsh
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        shell: /usr/bin/zsh
