---
- name: Dotfiles config
  hosts: localhost
  connection: local
  tasks:
    - name: Playbook directory
      ansible.builtin.debug:
        msg: "'{{ playbook_dir }}' is the playbook directory."

    - name: Set user_dir and user_id vars
      ansible.builtin.set_fact:
        user_dir: "{{ ansible_facts['user_dir'] }}"
        user_id: "{{ ansible_facts['user_id'] }}"

    - name: Create Directories
      ansible.builtin.include_tasks: "tasks/directories.yml"

    - name: Clone needed repos
      ansible.builtin.include_tasks: "tasks/clone.yml"

    - name: Symlink configs
      ansible.builtin.include_tasks: "tasks/symlink.yml"

    - name: Install Packages
      ansible.builtin.include_tasks: "tasks/packages.yml"

    - name: Change user default shell to zsh
      become: true
      tags:
        - zsh
      ansible.builtin.user:
        name: "{{ user_id }}"
        shell: /usr/bin/zsh
