---
- name: Dotfiles config
  hosts: localhost
  connection: local
  tasks:
    - name: Get user
      become: true # become sudo
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_user_id }}"

    - name: Create Directories
      ansible.builtin.include_tasks: "tasks/directories.yml"

    - name: Install Packages
      ansible.builtin.include_tasks: "tasks/packages.yml"

    - name: Install AUR Packages
      ansible.builtin.include_tasks: "tasks/aur.yml"

    - name: Setup ZSH
      ansible.builtin.include_tasks: "tasks/zsh.yml"
      tags:
        - zsh

    # Dotfiles
    # TODO: this isn't needed (BUT IS GOOD TO HAVE FOR ANSIBLE-PULL) since this script is already in the dotfiles
    # - Move this to linux-bootsrap repo
    # - name: Clone dotfiles
    #   ansible.builtin.git:
    #     repo: 'https://github.com/notlad-p/dotfiles.git'
    #     version: main
    #     dest: "{{ ansible_env.HOME }}/projects"

    # # Paru
    # - name: Clone Paru (Arch User Repository helper)
    #   ansible.builtin.git:
    #     repo: 'https://aur.archlinux.org/paru.git'
    #     version: main
    #     dest: "{{ ansible_env.HOME }}/projects"
