---
# AUR collection
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: "0644"
    validate: "visudo -cf %s"

- name: Install paru using makepkg
  kewlfft.aur.aur:
    use: makepkg
    name: paru
    state: present

- name: Install AwesomeWM git
  tags:
    - awesome
  kewlfft.aur.aur:
    use: paru
    name: awesome-git
    state: present

- name: Install Fast Node Manager (fnm)
  tags:
    - nodejs
  kewlfft.aur.aur:
    use: paru
    name: fnm-bin
    state: present

- name: Install AUR applications
  tags:
    - apps
  kewlfft.aur.aur:
    use: paru
    name:
      - onlyoffice-bin # office tools
      - spotify # cool sound waves
      - teams-for-linux # microshit
      - vesktop-bin
    state: present
