---
# clone all configs (and make sure they're updated)

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "https://github.com/notlad-p/dotfiles.git"
    version: main
    dest: "{{ ansible_env.HOME }}/projects"
- name: Clone NeoVim config
  ansible.builtin.git:
    repo: "https://github.com/notlad-p/nvim.git"
    version: master
    dest: "{{ ansible_env.HOME }}/.config"
- name: Clone AwesomeWM config
  ansible.builtin.git:
    repo: "https://github.com/notlad-p/awesome.git"
    version: master
    recursive: true # to clone submodules (defaults to true but better safe than sorry)
    dest: "{{ ansible_env.HOME }}/.config"
