---
# Terminal configs
- name: Symlink Kitty config
  tags:
    - kitty
  ansible.builtin.file:
    src: "~/projects/dotfiles/kitty"
    dest: "~/.config/kitty"
    state: link

- name: Symlink TMUX config
  tags:
    - tmux
  ansible.builtin.file:
    src: "~/projects/dotfiles/tmux"
    dest: "~/.config/tmux"
    state: link

- name: Symlink Starship config
  tags:
    - starship
  ansible.builtin.file:
    src: "~/projects/dotfiles/starship.toml"
    dest: "~/.config/starship.toml"
    state: link

- name: Symlink ZSH config
  tags:
    - zsh
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/projects/dotfiles/zsh", dest: "~/.config/zsh" }
    - { src: "~/projects/dotfiles/zsh/.zshenv", dest: "~/.zshenv" }

- name: Symlink Nvidia config (for 3 monitor setup at home)
  become: true
  tags:
    # - never # skip this task by default
    - personal
    - home-setup
  ansible.builtin.file:
    src: "~/projects/dotfiles/xorg.conf.d/10-nvidia.conf"
    dest: "/etc/X11/xorg.conf.d/10-nvidia.conf"
    state: link

# TODO: nvim
# TODO: yazi

# NOTE: I now use ZSH and Kitty, so these tasks are skipped unless the 'fish' or 'wezterm' tags are specified
- name: Symlink fish config
  tags:
    - never # skip this task by default
    - fish
  ansible.builtin.file:
    src: "~/projects/dotfiles/config.fish"
    dest: "~/.config/fish/config.fish"
    state: link

- name: Symlink WezTerm config
  tags:
    - never # skip this task by default
    - wezterm
  ansible.builtin.file:
    src: "~/projects/dotfiles/wezterm"
    dest: "~/.config/wezterm"
    state: link

# Desktop Environment
- name: Symlink Hyprland config
  tags:
    - desktop-environment
  ansible.builtin.file:
    src: "~/projects/dotfiles/wezterm"
    dest: "~/.config/wezterm"
    state: link
